name: CI - Run Tests

# --- Trigger ---
# This workflow runs on pushes to the 'main' branch and on any pull request targeting the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# --- Jobs ---
# A workflow is made up of one or more jobs that run in parallel or sequentially
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code into the runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the correct Node.js version
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run the tests
      - name: Run tests
        run: npm test